<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
	  <PackageReference Include="Azure.Storage.Files.Shares" Version="12.25.0" />
	  <PackageReference Include="Refit" Version="9.0.2" />
	  <PackageReference Include="Ulid" Version="1.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CtaCargo.CctImportacao.Domain\CtaCargo.CctImportacao.Domain.csproj" />
    <ProjectReference Include="..\CtaCargo.CctImportacao.Infrastructure.CrossCutting\CtaCargo.CctImportacao.Infrastructure.CrossCutting.csproj" />
    <ProjectReference Include="..\CtaCargo.CctImportacao.Infrastructure.Data\CtaCargo.CctImportacao.Infrastructure.Data.csproj" />
  </ItemGroup>

</Project>
